### ISSUE TITLE
Any release yet?

### ISSUE THREAD

**Issue by tanekim77** [lukaskabrt/PoExtractor#52]
It seems new version of PoExtractor has not been released to nuget packages since late 2017. Is there any plan to do so? If not, can I create my own fork of this repo and release it in the nuget?

**Comment by lukaskabrt** [comment]
Hello, the last release was made 2 months ago. Please see https://www.nuget.org/packages/PoExtractor/0.5.0
________________________________
From: tanekim77 ***@***.***>
Sent: Sunday, July 25, 2021 7:18:46 AM
To: lukaskabrt/PoExtractor ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [lukaskabrt/PoExtractor] Any release yet? (#52)


It seems PoExtractor has not been released to nuget packages since 2017. Is there any plan to do so? If not, can I create my own fork of this repo and release it in the nuget?

**Comment by tanekim77** [comment]
Thanks! Sound great!
